git config --global alias.st "status"
git config --global alias.ci "commit"
git config --global alias.co "checkout"
git config --global alias.df "diff"
git config --global alias.br "branch"
git config --global alias.hist "log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short"
git config --global alias.ch "checkout HEAD"
git config --global core.editor "vim "
git config --global core.excludesfile "~/.gitignore_global"
git config --global core.autocrlf "input"
git config --global core.whitespace "trailing-space,space-before-tab,indent-with-non-tab"
git config --global core.filemode "false"
git config --global color.ui "auto"
git config --global pull.rebase "true"
git config --global oh-my-zsh.hide-dirty "1"
